# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Sticky Agile
tagline:          'Agile Coaching'
description:      'A cooperative of Agile coaches offering a variety of classes for your business.'
url:              https://sticky-agile.github.io
baseurl:          /

author:
  name:           'Newton Meters'
  url:            https://newtonmeters.com

# Custom vars
version:          1.0.0

github:
  repo:           
