# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Sticky Agile
tagline:          'Agile Coaching'
description:      'A cooperative of Certified Scrum Trainers® and Agile Coaches collectively offering your organization 80 plus years of Scrum and Agile experience.'
url:              https://sticky-agile.github.io
baseurl:          

author:
  name:           'Newton Meters'
  url:            https://newtonmeters.com

# Custom vars
version:          1.0.0

github:
  repo:           
